### ISSUE TITLE
Question about message size

### ISSUE THREAD

**Issue by voidstarstar** [puniverse/galaxy#38]
This is probably a stupid question with a simple answer, but I can't seem to figure out which knob to turn.

How do you send large messages without crashing?  I either get a `Channel exception: java.io.IOException Message too long` error for the example below or the process seems to just hang for even larger sizes.

To reproduce the bug is simple.  Using the distributed [ping pong example](https://github.com/puniverse/quasar/tree/master/quasar-galaxy/src/test/java/co/paralleluniverse/galaxy/example/pingpong), simply add a new field to the [`Message`](https://github.com/puniverse/quasar/blob/master/quasar-galaxy/src/test/java/co/paralleluniverse/galaxy/example/pingpong/Message.java) class with a large enough size:
```java
final byte[] bar = new byte[102400];
```

I am using JGroups in case that is relevant.

Thanks!

**Comment by voidstarstar** [comment]
Ok, it looks like this is described in detail [here](http://blog.paralleluniverse.co/2012/08/09/galaxy-internals-part-3/).

>Packets are configured to have a maximum size, which should optimally be slightly less than the maximum Ethernet packet size, with some room left for IP and UDP headers (this is why jumbo frames are recommended when using Galaxy). **A packet can contain many messages, but a single message cannot be broken up into more than one packet, and this is why all Galaxy items must be smaller than the maximum packet size** (and, besides, small items are good in general as they would probably be less contended). If the packet is full, remaining messages are left to wait in the queue.

(emphasis mine)

For my specific application, I am aggregating many small messages into a larger message since this larger message must be processed atomically.  I assume that the best accepted practice would be to simply send the small messages as they are produced and just block on the receiving end until all arrive.

Are there any plans to abstract this away from the user in case the data is able to be physically split up, but unable to be easily logically split up?  Since Galaxy already knows the maximum size for a message, it seems fitting that it should handle splitting up messages.

**Comment by pron** [comment]
We are working on removing this limit.

**Comment by voidstarstar** [comment]
Great!  Thanks!

**Comment by disposableme** [comment]
Has this issue been solved @pron ?  If not, should it be reopened?

This issue makes using distributed Actors very inefficient for large messages.  Is there any optimal workaround that can be done by someone using an unmodified Galaxy library?  My current approach was to split a Message into smaller "logical" messages, but I have no way of knowing what size to make them since I'm sure the Message is being serialized and then compressed before being sent on the packet.  This means that if I just make an educated guess, I will still have wasted space in most packets.  Throughput is critical for my application so I will probably need to send messages through a proxy (and bypass the Actor Message system entirely) if this is not yet solved.

Related Question:  If one or more Actors on machine A send many small messages to one or more Actors on machine B, how do the messages get buffered?  Is this outsourced to another library?  Is something similar to Nagle's algorithm done and if so is there a flag to turn this on/off?

**Comment by pron** [comment]
Hi. This issue has been fixed, but not released yet. Galaxy is now in the midst of a major revamp (in a private repo). We expect to release it very soon (about a month, I think).

**Comment by disposableme** [comment]
Excellent!  I'm looking forward to the release!  Thanks for the amazing work on the whole software suite you have here!
